- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    
    - name: Red Hat Version
      shell: cat /etc/redhat-release
      register: rhel_version
      
    - name: Show Version
      debug:
        msg: "{{ rhel_version }}"

